name: 'Build and run tests'

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build ./SoftUniDemo/SoftUniDemo.csproj --configuration Release
    - name: Run tests
      run: dotnet test ./SoftUniDemoTests/SoftUniDemoTests.csproj
